name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to Pages folder
        run: |
          mkdir -p ./public
          cp -r * ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4